// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import SetAvatarReducer from "../set_avatar_reducer";
import SetUsernameReducer from "../set_username_reducer";

export type SetAvatarParams = __Infer<typeof SetAvatarReducer>;
export type SetUsernameParams = __Infer<typeof SetUsernameReducer>;
