// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
    TypeBuilder as __TypeBuilder,
    t as __t,
    type AlgebraicTypeType as __AlgebraicTypeType,
    type Infer as __Infer
} from "spacetimedb";
import { ReceiverIdentity } from "./types";

export default __t.row({
    sender: __t.identity(),
    get receiver() {
        return ReceiverIdentity;
    },
    startAt: __t.timestamp().name("start_at")
});
