// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
    TypeBuilder as __TypeBuilder,
    t as __t,
    type AlgebraicTypeType as __AlgebraicTypeType,
    type Infer as __Infer
} from "spacetimedb";
import { ReceiverIdentity } from "./types";

export default __t.row({
    id: __t.u256(),
    get receiver() {
        return ReceiverIdentity;
    },
    sender: __t.identity(),
    message: __t.string(),
    createdAt: __t.timestamp().name("created_at"),
    updatedAt: __t.timestamp().name("updated_at")
});
