// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
    TypeBuilder as __TypeBuilder,
    t as __t,
    type AlgebraicTypeType as __AlgebraicTypeType,
    type Infer as __Infer
} from "spacetimedb";

export const User = __t.object("User", {
    identity: __t.identity(),
    get status() {
        return UserStatus;
    },
    username: __t.option(__t.string()),
    avatar: __t.option(__t.byteArray())
});
export type User = __Infer<typeof User>;

// The tagged union or sum type for the algebraic type `UserStatus`.
export const UserStatus = __t.enum("UserStatus", {
    Online: __t.unit(),
    Offline: __t.timestamp(),
    OnCall: __t.unit()
});
export type UserStatus = __Infer<typeof UserStatus>;
